"""Fix TrainingPlan unique User

Revision ID: 106fd6fd352b
Revises: 27c759da56fe
Create Date: 2025-07-22 03:52:11.481763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106fd6fd352b'
down_revision: Union[str, Sequence[str], None] = '27c759da56fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'training_plans', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_plans', type_='unique')
    # ### end Alembic commands ###
