"""Upgraded User

Revision ID: 91dd39c523e3
Revises: f31d38b6408c
Create Date: 2025-07-16 18:44:51.489449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91dd39c523e3'
down_revision: Union[str, Sequence[str], None] = 'f31d38b6408c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activity_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activity_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
