"""Renamed User fields

Revision ID: d77914f92095
Revises: fcf3f7e653c1
Create Date: 2025-07-19 14:40:06.652010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77914f92095'
down_revision: Union[str, Sequence[str], None] = 'fcf3f7e653c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=False))
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'weight_kg')
    # ### end Alembic commands ###
